# Generated by Django 5.0.14 on 2026-07-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='userbook',
            options={'ordering': ['-updated_at']},
        ),
    ]